# Generated by Django 5.1.2 on 2024-10-18 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0002_alter_plantag_id_wallet_wallettransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="refund_details",
            field=models.JSONField(
                blank=True,
                help_text="Additional details for refund transactions",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="related_transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="Related transaction (for refunds)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds",
                to="subscription.wallettransaction",
            ),
        ),
    ]
