# Generated by Django 5.1.2 on 2024-10-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0003_wallettransaction_refund_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plancost",
            name="recurrence_unit",
            field=models.CharField(
                choices=[
                    ("once", "once"),
                    ("second", "second"),
                    ("minute", "minute"),
                    ("hour", "hour"),
                    ("day", "day"),
                    ("week", "week"),
                    ("month", "month"),
                    ("year", "year"),
                ],
                default="month",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionErrorLog",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("payment_failed", "PAYMENT_FAILED"),
                            ("insufficient_funds", "INSUFFICIENT_FUNDS"),
                            ("validation_error", "VALIDATION_ERROR"),
                            ("refund_error", "REFUND_ERROR"),
                            ("state_transition_error", "STATE_TRANSITION_ERROR"),
                            ("system_error", "SYSTEM_ERROR"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subscription_id", models.UUIDField()),
                ("user_id", models.UUIDField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField()),
                ("retry_count", models.IntegerField(default=0)),
                ("resolved", models.BooleanField(default=False)),
                ("resolution_timestamp", models.DateTimeField(null=True)),
                (
                    "retry_strategy",
                    models.CharField(
                        choices=[
                            ("immediate", "IMMEDIATE"),
                            ("exponential_backoff", "EXPONENTIAL_BACKOFF"),
                            ("fixed_interval", "FIXED_INTERVAL"),
                            ("manual", "MANUAL"),
                        ],
                        default="exponential_backoff",
                        max_length=50,
                    ),
                ),
                ("next_retry_time", models.DateTimeField(null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["subscription_id", "resolved"],
                        name="subscriptio_subscri_67d577_idx",
                    ),
                    models.Index(
                        fields=["error_type", "resolved"],
                        name="subscriptio_error_t_ea0883_idx",
                    ),
                    models.Index(
                        fields=["next_retry_time"],
                        name="subscriptio_next_re_412144_idx",
                    ),
                ],
            },
        ),
    ]
