# Generated by Django 5.1.2 on 2024-10-19 21:27

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0004_alter_plancost_recurrence_unit_subscriptionerrorlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionerrorlog",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
