# Generated by Django 5.1.2 on 2024-10-20 10:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0005_alter_subscriptionerrorlog_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.SlugField(
                        help_text="Unique code used to check feature access in code",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("boolean", "BOOLEAN"),
                            ("quota", "QUOTA"),
                            ("rate", "RATE"),
                            ("usage", "USAGE"),
                        ],
                        default="boolean",
                        max_length=20,
                    ),
                ),
                (
                    "pricing_model",
                    models.CharField(
                        choices=[
                            ("flat", "FLAT"),
                            ("tiered", "TIERED"),
                            ("volume", "VOLUME"),
                            ("package", "PACKAGE"),
                        ],
                        default="flat",
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit of measurement for quota/usage features",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this feature is enabled for the plan",
                    ),
                ),
                (
                    "quota",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum allowed quantity for quota features",
                        null=True,
                    ),
                ),
                (
                    "rate_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of operations allowed per time window",
                        null=True,
                    ),
                ),
                (
                    "rate_window",
                    models.DurationField(
                        blank=True, help_text="Time window for rate limiting", null=True
                    ),
                ),
                (
                    "overage_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost per unit when exceeding quota",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_features",
                        to="subscription.feature",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_features",
                        to="subscription.subscriptionplan",
                    ),
                ),
            ],
            options={
                "unique_together": {("plan", "feature")},
            },
        ),
        migrations.CreateModel(
            name="PricingTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_quantity",
                    models.IntegerField(help_text="Starting quantity for this tier"),
                ),
                (
                    "end_quantity",
                    models.IntegerField(
                        blank=True,
                        help_text="Ending quantity for this tier (null for unlimited)",
                        null=True,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit in this tier",
                        max_digits=10,
                    ),
                ),
                (
                    "flat_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fixed fee for this tier",
                        max_digits=10,
                    ),
                ),
                (
                    "plan_feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_tiers",
                        to="subscription.planfeature",
                    ),
                ),
            ],
            options={
                "ordering": ["start_quantity"],
            },
        ),
        migrations.CreateModel(
            name="FeatureUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("last_reset", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="subscription.feature",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_usage",
                        to="subscription.usersubscription",
                    ),
                ),
            ],
            options={
                "unique_together": {("subscription", "feature")},
            },
        ),
    ]
