# Generated by Django 5.1.2 on 2024-10-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0006_feature_planfeature_pricingtier_featureusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="is_feature_based",
            field=models.BooleanField(
                default=False, help_text="whether this plan is regular of feature based"
            ),
        ),
    ]
