# Generated by Django 5.1.2 on 2024-10-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0007_subscriptionplan_is_feature_based"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="reset_on_billing",
            field=models.BooleanField(
                default=True, help_text="Whether to reset usage counters on billing"
            ),
        ),
    ]
